// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk65gklkh6lN_LoSejK3ZnC2QlbTuIOtk',
    appId: '1:464204615333:web:367239d5b5cd97a605474c',
    messagingSenderId: '464204615333',
    projectId: 'taskly-8303f',
    authDomain: 'taskly-8303f.firebaseapp.com',
    databaseURL: 'https://taskly-8303f-default-rtdb.firebaseio.com',
    storageBucket: 'taskly-8303f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA94K2HOkS38qfxmeisd8YLMdS7hq3M2bw',
    appId: '1:464204615333:android:8be6df20c86058ae05474c',
    messagingSenderId: '464204615333',
    projectId: 'taskly-8303f',
    databaseURL: 'https://taskly-8303f-default-rtdb.firebaseio.com',
    storageBucket: 'taskly-8303f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjjo-2BI1dCpsUUckuvwSJz3qIBFQtrRs',
    appId: '1:464204615333:ios:900b20c434c2c34c05474c',
    messagingSenderId: '464204615333',
    projectId: 'taskly-8303f',
    databaseURL: 'https://taskly-8303f-default-rtdb.firebaseio.com',
    storageBucket: 'taskly-8303f.appspot.com',
    iosClientId: '464204615333-c532j8qibb1n32a6pjva2166p8dgpiog.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjjo-2BI1dCpsUUckuvwSJz3qIBFQtrRs',
    appId: '1:464204615333:ios:900b20c434c2c34c05474c',
    messagingSenderId: '464204615333',
    projectId: 'taskly-8303f',
    databaseURL: 'https://taskly-8303f-default-rtdb.firebaseio.com',
    storageBucket: 'taskly-8303f.appspot.com',
    iosClientId: '464204615333-c532j8qibb1n32a6pjva2166p8dgpiog.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskly',
  );
}
